### ISSUE TITLE
Some Chart, DrumRoll bar, Scroll speed issue

### ISSUE THREAD

**Issue by ryanlinjui** [JacobLinCool/rhythm-rs#4]
https://github.com/JacobLinCool/rhythm-rs/assets/57468611/703e3be5-5e9f-4923-bba3-a10bcb13a02c

Song: Nosferatu
Course: Oni
Play on Macbook M2 vscode terminal

----

## Chart has a little bit offset
You can see the end of song. Offset is happened.

## Scroll Speed is not BPM 200
As above said. I played like about BPM 300 speed, but BPM 200 should be correct.

## Some of DrumRoll Bars disappeared
Happened like 1:52. Not only this time but also others.

**Comment by JacobLinCool** [comment]
I'll investigate the music delay issue. Currently, the timer is not derived directly from the playback states, as Rodio does not provide such functionalities (the related issue is [here](https://github.com/RustAudio/rodio/issues/474)). Perhaps we need to consider using another music player library.

For the BPM problem, I'm not sure what the correct BPM should be. Currently, a note with 60 BPM and a scroll speed of x1 takes 5 seconds to pass through the whole track from right to left. Consequently, a note with 200 BPM takes 1.5 seconds to pass through the track. You can try reducing the width of the terminal to achieve a slower movement speed. Alternatively, my assumption of 5 seconds might be incorrect.

The disappearing drumroll bars are balloons or yems with a maximum hit count; they disappear as expected. Perhaps a UI improvement is necessary here to help players distinguish them.

**Comment by JacobLinCool** [comment]
Hi @ryanlinjui,

Commit https://github.com/JacobLinCool/rhythm-rs/commit/e2a17fa547ebae91411ab139da9815bfd01d4a2c gives the program some time to load the audio buffer before the game starts, which may resolve the delay issue. You may want to try it out.

**Comment by ryanlinjui** [comment]
It looks like no difference. Same issue that I said. Still has delay in the end of the song.
